name: GIthub Action with conditions
on:
  workflow_dispatch:
    inputs:
      my_input:
        description: "Input for this workflow"
        required: true
jobs:
  conditional-actions:
    if: github.repository == 'yawaiaung-devops/github-action'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Print input
        run: |
          echo "Input value: ${{ github.event.inputs.my_input }}"
